[package]
name = "bcs"
version = "0.1.0"
edition = "2024"

[dependencies]
natord = "1.0.9"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tantivy = "0.25.0"
time = { version = "0.3.44", features = ["parsing"] }
